# Generated by Django 2.2.7 on 2019-12-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20191204_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.IntegerField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.IntegerField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.IntegerField(verbose_name='Longitude'),
        ),
    ]
