# Generated by Django 3.0 on 2019-12-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20191204_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='forageing',
            field=models.BooleanField(default=True, verbose_name='Foraging'),
            preserve_default=False,
        ),
    ]
